ALTER DATABASE mosip_audit OWNER TO postgres;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA audit TO postgres;

REVOKE ALL PRIVILEGES ON DATABASE mosip_audit FROM audituser, sysadmin;

GRANT SELECT, INSERT, TRUNCATE, REFERENCES, UPDATE, DELETE ON ALL TABLES IN SCHEMA audit TO audituser;

ALTER TABLE audit.app_audit_log ALTER COLUMN host_ip TYPE varchar(256) USING host_ip::varchar;